name: base
channels: 
    - conda-forge
dependencies:
    - numpy
    # - proj=7.*.        # errors with cartopy when 6.2.* is used
    - cartopy
    - gdal
    - libgdal 
    - obspy
    - pandas
    - pip 
    - libiconv
    - xarray
    - jupytext
    - h5netcdf
    - netcdf4
    - xlrd
    - openpyxl
    - gfortran
    - pip:
      - lavavu
      - xvfbwrapper 
      - cloudstor
      - stripy
      - litho1pt0

      
      


