name: base
channels: 
    - conda-forge
    - geo-down-under    
dependencies:
    - python=3.7
    - cloudstor
    - stripy
    - litho1pt0
    - proj=7.*.        # errors with cartopy when 6.2.* is used
    - cartopy=0.18.*   # 0.17.?
    - gdal
    - libgdal  # ?
    - obspy
    - pandas
    - pip 
    - libiconv
    - xarray
    - jupytext
    - h5netcdf
    - pip:
      - lavavu<1.7
      - xvfbwrapper 

      
      


