name: Health check

on:
  schedule: 
    - cron:  '*/30 * * * *'  # Every 30 minutes

  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Request version via jupyterhub REST API
      run: |
        curl http://${{ secrets.DROPLET_IP }}/hub/api

       # Updates packages / reconfig tljh then reloads just in case
    - name: Reload hub if the health check failed
      if: failure()
      env:  
        SSHPASS: ${{ secrets.DROPLET_PASS }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} hostname
        sshpass -e ssh root@${{ secrets.DROPLET_IP }} "sudo tljh-config reload hub"
        
      
